# Generated by Django 5.1.7 on 2025-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rename_phone_customer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=100)),
                ('food_cat', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('img', models.URLField(default='', max_length=500)),
                ('res_address', models.CharField(max_length=200)),
            ],
        ),
    ]
