# Generated by Django 5.1.7 on 2025-03-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_restaurants_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_avial', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=50)),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurants')),
            ],
        ),
    ]
